---
abstract: 'Debug panel to inspect the Catalyst Session'
author:
  - 'Thomas Kuyper <tkuyper@cpan.org>'
build_requires:
  Catalyst::Test: 0
  FindBin: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-CatalystSession
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst: 5.90050
  Catalyst::Plugin::Session: 0
  Class::Method::Modifiers: 0
  Data::Dumper: 0
  HTML::Entities: 0
  Plack::Middleware::Debug: 0
  perl: 5.008
version: 0.01
